[features]
seeds = false
[programs.localnet]
anchor_game_ticket = "BvXkNSWxqAszoJyRU6eQJB6cYAWsk7JvsLt7JtHhks2b"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/mbenz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
