[features]
seeds = false
skip-lint = false
[programs.devnet]
auction = "73YJ31M6KX8FVH5g9mYEy7aHd3YYNFUsSP6EZCFe8iXo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
