[features]
seeds = false
skip-lint = false
[programs.devnet]
auction = "3AQ3XWGLWcWQ8BFf8VHKV2pz6YSimtAjaSbvHgZCsV5X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
