[features]
seeds = false
[programs.devnet]
#[programs.localnet]
anchor_raffle_ticket = "4coTofX2WZBYv1EA4Gr4N35687MH7iQj1sJSXuMrk2bV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
#cluster = "localnet"
wallet = "/Users/kob/.config/solana/id5.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
