[features]
seeds = false
skip-lint = false
[programs.devnet]
orao = "5YycSXWBQwXTciqF4VB638u7HB6AcJvGGWSH4H9F5Xxy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
