[features]
seeds = false
skip-lint = false
[programs.devnet]
gift = "4NtgP5gmSJFPoifmXS1Fw1zHGvwhguRNhzT5jP7u3U6A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
