[features]
seeds = false
#[programs.mainnet]
[programs.devnet]
#[programs.localnet]
#anchor_raffle_ticket = "Hjaw5obT3bWQazo4bASgzjuP1mRgXoXMFbwVroHbWPSC" 
anchor_raffle_ticket = "J9KjNChkP1mPneAX979w1zpGGNxdrVjoV5Y5NKtuK8pV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "mainnet"
cluster = "devnet"
#cluster = "localnet"
#wallet = "/Users/kob/.config/solana/id5.json"
#wallet = "~/.config/solana/programSigner.json"
wallet = "/home/mbenz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

