[features]
seeds = false
skip-lint = false
[programs.localnet]
wheel = "HsDXU6Ku6ggbqDzhxyrNLjby5MLdT7RXXnR6AhFChD7L"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/worker/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
